[package]
name = "ylangc"
version = "0.1.0"
authors = ["Yuhanun Citgez <y.citgez@student.utwente.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokenizer = { path="../tokenizer" }